name: 'Build $(Build.BuildId)'
variables:
  BUILD_CONFIGURATION: 'Release'
  FUNCTION_OUTPUT_DIRECTORY: '$(Build.SourcesDirectory)/function-app'
  STAGING_DIRECTORY: '$(Build.ArtifactStagingDirectory)'
  FUNCTION_DIRECTORY: '$(Build.SourcesDirectory)/src/Lively.Football.Function'
jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: all
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      configuration: '$(BUILD_CONFIGURATION)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--output $(FUNCTION_OUTPUT_DIRECTORY)'
      configuration: '$(BUILD_CONFIGURATION)'
      publishWebProjects: true
      workingDirectory: '$(FUNCTION_DIRECTORY)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(FUNCTION_OUTPUT_DIRECTORY)'
      includeRootFolder: false
      archiveFile: '$(STAGING_DIRECTORY)/Lively.Football.Function.zip'

  - task: PublishBuildArtifacts@1
      
      